routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('stargrid');
    return view('stargrid2');
    // return view('star_greed');
});

//prefijo de rutas
Route::group(['prefix' => 'admin'], function(){
Route::resource('users','UsersController');
Route::get('users/{id}/destroy',[
    'uses' =>'UsersController@destroy',
    'as' => 'users.destroy'
]);
// Route::resource('accounts','AccountsController');
Route::resource('activos','ActivosController');
Route::resource('activoncs','ActivoncsController');
Route::resource('gastosdvs','GastosdvsController');
Route::resource('gastosops','GastosopsController');
Route::resource('ingresos','IngresosController');
Route::resource('pasivoncs','PasivoncsController');
Route::resource('pasivopats','PasivopatsController');
Route::resource('diarios','DiariosController');

});

app/Pasivopat.php
<?php

namespace Crud;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pasivopat extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'cuenta', 'subcuenta',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    // protected $hidden = [
    //     'password', 'remember_token',
    // ];
}

app/Http/Controllers/PasivopatsController.php
<?php

namespace Crud\Http\Controllers;
use Crud\Pasivopat;
use Laracasts\Flash\Flash;
use Illuminate\Http\Request;

class PasivopatsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pasivopats = Pasivopat::orderBy('id','ASC')->paginate(5);
        return view('admin.pasivopats.index')->with('pasivopats', $pasivopats);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.pasivopats.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pasivopat=new Pasivopat($request->all());
       $pasivopat->save();
        Flash::warning("se ha insertado  " .$pasivopat->cuenta. "de forma exitosa");
       return redirect()->route('pasivopats.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pasivopat=Pasivopat::find($id);
        return view('admin.pasivopats.edit')->with('pasivopat',$pasivopat);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $pasivopat=Pasivopat::find($id);
       $pasivopat->cuenta=$request->cuenta;
       $pasivopat->subcuenta=$request->subcuenta;
       $pasivopat->save();
       Flash::warning('el usuario '. $pasivopat->cuenta . ' ha sido editado con exito!');
       return redirect()->route('pasivopats.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pasivopats/create.blade.php
@extends('admin.template.main')

@section('title', 'Crear cuenta')

@section('content')

    {!! Form::open(['route' => 'pasivopats.store', 'method' => 'POST']) !!}
    <div class="form-group">
    {!! Form::label('cuenta', 'Cuenta') !!}
    {!! Form::text('cuenta',null, ['class' => 'form-control', 'placeholder' => 'Nombre Cuenta', 'required']) !!}
    </div>
    <div class="form-group">
    {!! Form::label('subcuenta', 'Subcuenta') !!}
    {!! Form::text('subcuenta',null, ['class' => 'form-control', 'placeholder' => 'Nombre Subcuenta', 'required']) !!}
    </div>
    <!-- <div class="form-group">
    {!! Form::label('type', 'Tipo') !!}
    {!! Form::select('type', ['member' => 'Miembro', 'admin' => 'Administrador']) !!}
    </div> -->
    <div class="form-group">
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	</div>
    {!! Form::close() !!}

@endsection

resources/views/admin/pasivopats/edit.blade.php
@extends('admin.template.main')

@section('title', 'Editar Cuenta'.$pasivopat->cuenta)

@section('content')

    {!! Form::open(['route' => ['pasivopats.update',$pasivopat], 'method' => 'PUT']) !!}
    <div class="form-group">
    {!! Form::label('cuenta', 'Cuenta') !!}
    {!! Form::text('cuenta',$pasivopat->cuenta, ['class' => 'form-control', 'placeholder' => 'Nombre Cuenta', 'required']) !!}
    </div>
    <div class="form-group">
    {!! Form::label('subcuenta', 'Subcuenta') !!}
    {!! Form::text('subcuenta',$pasivopat->subcuenta, ['class' => 'form-control', 'placeholder' => 'Nombre Subcuenta', 'required']) !!}
    </div>
    <!-- <div class="form-group">
    {!! Form::label('type', 'Tipo') !!}
    {!! Form::select('type', ['member' => 'Miembro', 'admin' => 'Administrador']) !!}
    </div> -->
    <div class="form-group">
	{!!Form::submit('Editar',['class'=>'btn btn-primary'])!!}
	</div>
    {!! Form::close() !!}

@endsection

resources/views/admin/pasivopats/index.blade.php
@extends('admin.template.main')
@section('title','Lista de Cuentas')

@section('content')
<a href="{{ route('pasivopats.create') }}" class="btn btn-info">Registrar nueva cuenta</a>
<table class="table">
    <thead>
        <th>Id</th>
        <th>Cuenta</th>
        <th>Subcuenta</th>
        </thead>
    <tbody>
    @foreach($pasivopats as $pasivopat)
    <tr>
        <td>{{ $pasivopat->id }}</td>
        <td>{{ $pasivopat->cuenta }}</td>
        <td>{{ $pasivopat->subcuenta }}</td>
        <td>
        @if($pasivopat->type =="admin")
        <span class="label label-danger">{{ $pasivopat->type }}</span>
        @else
        <span class="label label-primary">{{ $pasivopat->type }}</span>
        @endif
        </td>
        <td><a href="{{ route('pasivopats.edit', $pasivopat->id)}}" class="btn btn-warning"><span class="glyphicon-wrench" aria-hidden="true"></span></a>
            <a href="{{ route('pasivopats.destroy', $pasivopat->id)}}" onclick="return confirm('¿Seguro deseas Eliminarlo')" class="btn btn-danger"><span class="glyphicon-remove-circle" aria-hidden="true"></span></a> </td>
    </tr>
@endforeach
    </tbody>
</table>
<div class="text-center">{!! $pasivopats->render() !!}</div>

@endsection