routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('stargrid');
    return view('stargrid2');
    // return view('star_greed');
});

//prefijo de rutas
Route::group(['prefix' => 'admin'], function(){
Route::resource('users','UsersController');
Route::get('users/{id}/destroy',[
    'uses' =>'UsersController@destroy',
    'as' => 'users.destroy'
]);
// Route::resource('accounts','AccountsController');
Route::resource('activos','ActivosController');
Route::resource('activoncs','ActivoncsController');
Route::resource('gastosdvs','GastosdvsController');
Route::resource('gastosops','GastosopsController');
Route::resource('ingresos','IngresosController');
Route::resource('pasivoncs','PasivoncsController');
Route::resource('pasivopats','PasivopatsController');
Route::resource('diarios','DiariosController');

});

app/Pasivonc.php
<?php

namespace Crud;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pasivonc extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'cuenta', 'subcuenta',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    // protected $hidden = [
    //     'password', 'remember_token',
    // ];
}

app/Http/Controllers/PasivoncsController.php
<?php

namespace Crud\Http\Controllers;
use Crud\Pasivonc;
use Laracasts\Flash\Flash;
use Illuminate\Http\Request;

class PasivoncsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pasivoncs = Pasivonc::orderBy('id','ASC')->paginate(5);
        return view('admin.pasivoncs.index')->with('pasivoncs', $pasivoncs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.pasivoncs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pasivonc=new Pasivonc($request->all());
       $pasivonc->save();
        Flash::warning("se ha insertado  " .$pasivonc->cuenta. "de forma exitosa");
       return redirect()->route('pasivoncs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pasivoncs/create.blade.php
@extends('admin.template.main')

@section('title', 'Crear cuenta')

@section('content')

    {!! Form::open(['route' => 'pasivoncs.store', 'method' => 'POST']) !!}
    <div class="form-group">
    {!! Form::label('cuenta', 'Cuenta') !!}
    {!! Form::text('cuenta',null, ['class' => 'form-control', 'placeholder' => 'Nombre Cuenta', 'required']) !!}
    </div>
    <div class="form-group">
    {!! Form::label('subcuenta', 'Subcuenta') !!}
    {!! Form::text('subcuenta',null, ['class' => 'form-control', 'placeholder' => 'Nombre Subcuenta', 'required']) !!}
    </div>
    <!-- <div class="form-group">
    {!! Form::label('type', 'Tipo') !!}
    {!! Form::select('type', ['member' => 'Miembro', 'admin' => 'Administrador']) !!}
    </div> -->
    <div class="form-group">
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	</div>
    {!! Form::close() !!}

@endsection

resources/views/admin/pasivoncs/index.blade.php
@extends('admin.template.main')
@section('title','Lista de Cuentas')

@section('content')
<a href="{{ route('pasivoncs.create') }}" class="btn btn-info">Registrar nueva cuenta</a>
<table class="table">
    <thead>
        <th>Id</th>
        <th>Cuenta</th>
        <th>Subcuenta</th>
        </thead>
    <tbody>
    @foreach($pasivoncs as $pasivonc)
    <tr>
        <td>{{ $pasivonc->id }}</td>
        <td>{{ $pasivonc->cuenta }}</td>
        <td>{{ $pasivonc->subcuenta }}</td>
        <td>
        @if($pasivonc->type =="admin")
        <span class="label label-danger">{{ $pasivonc->type }}</span>
        @else
        <span class="label label-primary">{{ $pasivonc->type }}</span>
        @endif
        </td>
        <td><a href="{{ route('pasivoncs.edit', $pasivonc->id)}}" class="btn btn-warning"><span class="glyphicon-wrench" aria-hidden="true"></span></a>
            <a href="{{ route('pasivoncs.destroy', $pasivonc->id)}}" onclick="return confirm('¿Seguro deseas Eliminarlo')" class="btn btn-danger"><span class="glyphicon-remove-circle" aria-hidden="true"></span></a> </td>
    </tr>
@endforeach
    </tbody>
</table>
<div class="text-center">{!! $pasivoncs->render() !!}</div>

@endsection